trajectories:
  # publishing frequency
  freq: 400

  # Circle parameters
  circle:
    center: 
      x: 0.3
      y: 0.0
      z: 0.3
    radius: 0.2
    normal_vector:
      x: 1.0
      y: 0.0
      z: 0.0

  # Line parameters
  line: 
    start:
      x: 0.35
      y: 0.35
      z: 0.7
    end:
      x: 0.0
      y: 0.35
      z: 0.7
      
  max_velocity: 0.2
  max_acceleration: 0.2
  frame_ID: map
  
  # Orientation of endeffector
  orientation:
    w: 0.0
    x: 0.0
    y: 0.0
    z: 1.0
