trajectories:
  # publishing frequency
  freq: 400

  # Circle parameters
  circle:
    center: 
      x: 0.3
      y: 0.0
      z: 0.3
    radius: 0.2
    normal_vector:
      x: 1.0
      y: 0.0
      z: 0.0

  # Line parameters
  line: 
    start:
      x: 1.3
      y: -0.2
      z: 0.8
    end:
      x: 1.5
      y: 0.1
      z: 0.6
      
  max_velocity: 0.2
  max_acceleration: 0.2

