# publishing
freq: 200 # publishing frequency
commandPublisherTopic: /huskanypulator/highlevel_controller/ee_state_command
actionServerName: /genEETrajectory


# Circle parameters
circle:
  center: 
    x: 0.3
    y: 0.0
    z: 0.3
  radius: 0.2
  normal_vector:
    x: 1.0
    y: 0.0
    z: 0.0

# Line parameters
line: 
  start:
    x: 0.45
    y: -0.13
    z: 0.70
  end:
    x: 0.45
    y: 0.10
    z: 0.70
    
max_velocity: 0.03
max_acceleration: 0.03
frame_ID: base_link

# Orientation of endeffector
orientation:
  w: 1.0
  x: 0.0
  y: 0.0
  z: 0.0

# Frame id of the endeffector
EE_frame_ID: TOOL

joystick:
  step_length_gain: 0.02; # [s] multiplicator to the velocity for incremental position update
  vel_min: 0.005 # [m/s] minimum commanded velocity below which command will be ignored