trajectories:
  # publishing frequency
  freq: 400

  # Circle parameters
  circle:
    center: 
      x: 0.3
      y: 0.0
      z: 0.3
    radius: 0.2
    normal_vector:
      x: 1.0
      y: 0.0
      z: 0.0

  # Line parameters
  line: 
    start:
      x: 0.2
      y: 0.2
      z: -0.1
    end:
      x: 0.2
      y: -0.1
      z: -0.2
      
  max_velocity: 0.3
  max_acceleration: 0.2
  frame_ID: panel_link
  
  # Orientation of endeffector
  orientation:
    w: 0.0
    x: 0.0
    y: 0.0
    z: 1.0
